variable "deployment-id" {
  description = "Logical name to identify the application resources in aws accoount."
}

variable "aws-profile" {
}

variable "aws-region" {
}

variable "create-credit-balance-alarm-fn" {
  default = "create-cpu-credit-balance-alarm"
}

variable "create-cpu-utilization-alarm-fn" {
  default = "create-cpu-baseline-utilization-alarm"
}

variable "cpu-credit-composite-fn" {
  default = "create-cpu-credit-balance-and-utlization-alarm"
}

variable "check-instance-type-fn" {
  default = "check-for-instance-class"
}

variable "remove-alarms-fn" {
  default = "remove-cpu-credits-balance-alarm"
}

variable "check-composite-alarm-fn" {
  default = "check-for-cpu-credit-composite-alarm"
}

variable "send-composite-alarm-to-email-group-fn" {
  default = "suppress-or-send-composite-alarm-to-email-group"
}

variable "send-composite-alarm-to-ms-teams-fn" {
  default = "suppress-or-send-composite-alarm-to-ms-teams"
}

variable "composite-alarm-sns-topic" {
  default = "receive-notification-from-cpu-credit-composite-alarm"
}

variable "end-subscribers-sns-topic" {
  default = "receive-ec2-notifications"
}

variable "apigateway-suffix" {
  default = "configure-cpu-credit-balance-alarms"
}

variable "logs-retention-period" {
  default     = "7"
  description = "The duration in days to retain the cloudwatch logs of lambda functions."
}

variable "suppress-alarms-prefix" {
  default = "suppress-alarm"
}

variable "placeholder-ms-teams-web-hook-url" {
  default     = "https://dummy.webhook.office.com/webhookb2/1181e5ca-2d49-4c88-ae44-603f377079b7@36da45f1-dd2c-4d1f-af13-5abe46b99921/IncomingWebhook/5ee2b91595bd45b48525c5c4e137e218/0ed140b9-97d5-467c-a2d7-31361c0734c0"
  description = "URL of MS Teams channel Webhook where notifications are published. The value can be modifed from the SSM parameter store."
}

variable "aws-powertools-and-more-lambda-layer-suffix" {
  default = "ec2-lambda-layer-aws-lambda-powertools-and-more"
}

variable "suppress-api-uri" {
  default     = "suppress-cpu-credit-alarm"
  description = "URI of API which tags the instance to suppress future notifications."
}

variable "compute-intensive-workloads-regix-list" {
  default     = "batch1,batch2"
  description = "List of substrings of application names which require additonal datapoints for the alarm."
}

variable "part-name-of-s3-bucket-for-generated-cloudwatch-metric-images" {
  default     = "metric-images"
  description = "Part of the bucket's name which stores the images of cloudwatch metric pictures generated by the lambda function."
}

variable "main-event-bus" {
  default     = "ec2-event-bus"
  description = "The main event bus which orchestrates cpu alarms creation and notification flow."
}

variable "ec2-state-change-notification-event-detail-type" {
  default = "EC2 Instance State-change Notification"
}

variable "lambda-layer-name-suffix" {
  default     = "ec2-lambda-layer"
  description = "Part of the lambda layer's name"
}

variable "outcome-to-trigger-downstream-send-alarm-notification-fns" {
  default = "Send Alarm Notification To Subscribers"
}

variable "suppress-notification-or-generate-metric-images-fn" {
  default = "suppress-notification-or-generate-metric-images"
}

variable "period-of-evaluation-for-each-datapoint" {
  default = 300
  description = "Default alarm Period. The value can be modifed from the SSM parameter."
}

variable "number-of-datapoints-to-evaluate" {
  default = 2
  description = "Default alarm Datapoints. The value can be modifed from the SSM parameter."
}

variable "number-of-evaluation-periods" {
  default = 2
  description = "Default alarm Evaluation Periods. The value can be modifed from the SSM parameter."
}

variable "number-of-cpu-credits-per-vcpu-hour" {
  default = 60
  description = "Default cpu credit alarm Threshold. The value can be modifed from the SSM parameter."
}

variable "outcome-to-trigger-check-composite-alarm-fn" {
  default = "Instance Is Of Burstable Class"
}

variable "notification-from-check-instance-class-fn" {
  default = "Checked Instance Class Function Notification"
}

variable "outcome-to-trigger-create-cpu-credit-alarm-fn" {
  default = "Create CPU-Credit Alarm As Composite Alarm Is Not Avialable"
}

variable "notification-from-check-composite-alarm-fn" {
  default = "Checked Composite Alarm Function Notification"
}

variable "notification-from-create-cpu-credit-balance-alarm-fn" {
  default = "Create-CPU-Credit-Balance Alarm Function Notification"
}

variable "outcome-to-trigger-create-cpu-utilization-alarm-fn" {
  default = "Created CPU-Credit-Balance Alarm"
}

variable "notification-from-create-cpu-utilization-alarm-fn" {
  default = "Create-CPU-Utilization Alarm Function Notification"
}

variable "outcome-to-trigger-create-cpu-credit-composite-alarm-fn" {
  default = "Created CPU-Utilization Alarm. Both Child Alarms[CPU and Credit] Now Exists."
}

variable "notification-from-suppress-notification-or-generate-metric-images-fn" {
  default = "Suppress-Notification-Or-Generate-Metric-Images Function Notification"
}

variable "suppress-tag" {
  default = "SuppressCpuCreditAlarm"
}

variable "maintenance-operations-sns-topic" {
  default = "receive-notification-to-create-or-update-alarms-for-existing-ec2"
}

variable "maintenance-operations-lambda-and-event-rule" {
  default = "create-or-update-alarms-for-existing-instance"
}

variable "notification-to-create-alarms-for-existing-instance" {
  default = "Create Alarm For Existing Instance Notification"
}

variable "notification-to-update-alarms" {
  default = "Update Alarm Notification"
}

variable "operation-type-to-create-alarm" {
  default = "ec2-create-alarm"
}

variable "operation-type-to-update-alarm" {
  default = "ec2-update-alarm"
}

